name: Verify Commit Emails

on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  commit-check:
    name: Commit Check
    if: contains(fromJSON('["bakito", "fbuehlmann" ,"zbindenp"]'), github.actor)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Check author email domain
        uses: commit-check/commit-check-action@fd3d923eab0876650f261d2a75572e8161a9a58e # v2.16.0
        with:
          author-email: true
          author-name: false
          message: false
          branch: false
        env:
          CCHK_AUTHOR_EMAIL_PATTERN: "^.+@bison-group\\.com$"
